// Mocks generated by Mockito 5.4.6 from annotations
// in product_clean_architecture/test/feature/product/data/repositories/product_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:product_clean_architecture/core/network/base_response/base_response.dart'
    as _i4;
import 'package:product_clean_architecture/feature/product/api/data_source_impl/product_remote_data_source_impl.dart'
    as _i2;
import 'package:product_clean_architecture/feature/product/data/models/productModels.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProductRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSourceImpl extends _i1.Mock
    implements _i2.ProductRemoteDataSourceImpl {
  MockProductRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<List<_i5.productModels>>> getProducts({
    int? page,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {#page: page, #limit: limit}),
            returnValue:
                _i3.Future<_i4.BaseResponse<List<_i5.productModels>>>.value(
                  _i6.dummyValue<_i4.BaseResponse<List<_i5.productModels>>>(
                    this,
                    Invocation.method(#getProducts, [], {
                      #page: page,
                      #limit: limit,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<List<_i5.productModels>>>);
}
